# Generated by Django 3.2.7 on 2021-09-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachineInterfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=39)),
                ('status', models.CharField(max_length=10)),
                ('mac_adress', models.CharField(max_length=50)),
                ('mtu', models.PositiveIntegerField()),
            ],
        ),
    ]
