# Generated by Django 3.2.7 on 2021-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachineinterfaces',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=39),
        ),
    ]
